baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'HNO Wucherpfenning'
theme = 'hugo-arcana'
copyright = "© {currentYear} HNO Wucherpfenning"



[menu]
  [[menu.main]]
    name = "PRAXIS"
    url = "/praxis/"
    # weight bestimmt die Reihenfolge
    weight = 1

  [[menu.main]]
    name = "TEAM"
    url = "/team/"
    weight = 2

  [[menu.main]]
    name = "SPRECHZEITEN"
    url = "/sprechzeiten/"
    weight = 5

  [[menu.main]]
    name = "LEISTUNGEN"
    url = "/leistungen/"
    weight = 3

  [[menu.main]]
    name = "KONTAKT"
    url = "/kontakt/"
    weight = 4

  [params.footer]
    [params.footer.contact_form]
      enabled = true

    [[params.footer.links]]
      header = "Links"
    [[params.footer.links.links]]
      title = "Kontakt"
      url = "/kontakt/"
    [[params.footer.links.links]]
      title = "Impressum"
      url = "/impressum/"
    [[params.footer.links.links]]
      title = "Datenschutz"
      url = "/datenschutz/"
    