[build]
  publish = "public"
  command = "hugo"



[context.production.environment]
  HUGO_VERSION = "0.147.0" 
  HUGO_ENABLEGITINFO = "true"
  HUGO_ENV = "production"
  GO_VERSION = "1.24.2"
  NODE_VERSION = "18"

