[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.121.1"  # oder deine gewünschte Hugo-Version
  GO_VERSION = "1.20"  # oder 1.21 – je nach Kompatibilität